### ISSUE TITLE
sax error

### ISSUE THREAD

**Issue by HarolddeBruijn** [pafnow/vrt-graphml-for-yed#2]
When importing a set in yEd (v 3.18.0.2) a sax error is returned.

edit -> manage palette -> import section

SAX error: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

same error occurs when opening the graphml file on its own.

**Comment by FibreFoX** [comment]
Hm, maybe your file is corrupted? Using 3.18.1.1 on Windows 10 has no problems at all.

**Comment by itthing** [comment]
I'm using 3.18.2 on Windows 10 and having the same issue.

**Comment by itthing** [comment]
Ah, I figured out I downloaded the graphml files incorrectly, getting HTML instead of the XML.  Instead of right-clicking "save target as" to download the files in the list, I selected the download link to get a zip of the graphml files.

**Comment by HarolddeBruijn** [comment]
Closing issue as it is aged.
