### ISSUE TITLE
vrt-files can't be open with yEd V3.20.1

### ISSUE THREAD

**Issue by powerbiker** [pafnow/vrt-graphml-for-yed#5]
Hello, the following error appears when opening the VRT files!
![grafik](https://user-images.githubusercontent.com/28304398/111163529-7721de00-859d-11eb-92eb-541e60e8a317.png)

**Comment by alexandreracine** [comment]
I use 3.21.1 and it works. Maybe update?

1. Open software
2. Right clic on one section of the Palette tab (ex: People)
3. Choose "manage palette"
4. Choose "Import Section" and point to the "VRT Clients and Peripherals.graphml" file.
5. A new section should be added. Do the same for all files.

With this method, the new section will always be there. I guess, don't delete the files tho.

**Comment by powerbiker** [comment]
I have yEd V 3.20.1 and no newer update available.
With the method described, the section is created, but no symbols are displayed!
![grafik](https://user-images.githubusercontent.com/28304398/112267763-3baaa200-8c76-11eb-8ab8-d95a23bd5a96.png)

**Comment by alexandreracine** [comment]
yEd last version here : https://www.yworks.com/products/yed


![image](https://user-images.githubusercontent.com/5158041/112383139-1d1ec800-8cc3-11eb-8bfb-bb1a032db84c.png)

**Comment by powerbiker** [comment]
after update to V3.21.1 still the same problem!
Palette ToolTip: palette "xy-file" can not be load: SAX error: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

![grafik](https://user-images.githubusercontent.com/28304398/112439433-6285d880-8d49-11eb-874a-859035eda3ce.png)

**Comment by powerbiker** [comment]
system environment: Windows 10 Pro
V 10.0.19042
![grafik](https://user-images.githubusercontent.com/28304398/112440882-1fc50000-8d4b-11eb-98ac-0eecddadfe6d.png)

**Comment by spectator7845** [comment]
Same issue here with a fresh install of yED 3.21.1. My environment ist "Linux Mint 20.1 Cinnamon" and I used the yEd Linux installer with the integrated JRE.

**Comment by Meilenstein** [comment]
Same here on Mac OS X with yED 3.21.1
But only with VRT Energy Management.graphml
With the other ones I have no problems.

**Comment by steeplight** [comment]
I had the same issue.
The problem: was my stupidity - i was downloading the html not the actual file from github
Solution: just downloaded the zip files required and after that unziped them and imported them:

new palette in yED through Edit > Manage Palette > Import Section

I hope this will help for future missclicks:)
